language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - coverage run --append ./l10n_slovnik file.tmx
  - coverage run --append ./l10n_slovnik file.tbx
  - coverage run --append ./l10n_slovnik || true
  - coverage run --append ./l10n_slovnik invalid || true
  - pycodestyle l10n_slovnik
  - pylint --reports=n l10n_slovnik
  - pyflakes l10n_slovnik
after_script:
  - codecov
