[tool.isort]
profile = "black"

[tool.ruff]
format = "github"
ignore = ["D211", "D212", "D100", "D104", "D101", "T201"]
select = ["E", "F", "B", "A", "C4", "DJ", "D", "ERA", "EXE", "G", "T20", "RET", "SLF", "N"]

[tool.ruff.mccabe]
max-complexity = 16
