[tool.isort]
profile = "black"

[tool.ruff]
ignore = [
  "ANN",
  "S310",
  "PLW2901",  # TODO
  "PIE810",  # TODO
  "PLR2004",
  "D211",
  "D212",
  "D100",
  "D104",
  "D101",
  "T201"
]
output-format = "github"
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 16
