name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - run: pip install -r requirements-test.txt
    - run: coverage run --append ./l10n_slovnik file.tmx
    - run: coverage run --append ./l10n_slovnik file.tbx
    - run: coverage run --append ./l10n_slovnik || true
    - run: coverage run --append ./l10n_slovnik invalid || true
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
